run:
  tests: false
#   # timeout for analysis, e.g. 30s, 5m, default is 1m
#   timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - errname
    - exportloopref
#    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - revive
    - text: "don't use an underscore in package name"
      linters:
        - revive
    - text: "don't use underscores in Go names; const (TxEndpoint|TLCategory|TLType|TLAction)_"
      linters:
        - revive
    - text: "ST1003:"
      linters:
        - stylecheck
    - text: "don't use leading k in Go names"
      linters:
        - revive
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd

          - github.com/armon/go-metrics

          - cosmossdk.io/api
          - cosmossdk.io/client/v2/autocli
          - cosmossdk.io/core
          - cosmossdk.io/errors
          - cosmossdk.io/log
          - cosmossdk.io/math
          - cosmossdk.io/store
          - cosmossdk.io/x/evidence
          - cosmossdk.io/x/feegrant
          - cosmossdk.io/x/tx/signing
          - cosmossdk.io/x/upgrade
          - github.com/cosmos/cosmos-db
          - github.com/cosmos/cosmos-sdk
          - github.com/cosmos/go-bip39
          - github.com/cosmos/ibc-apps
          - github.com/cosmos/ibc-go

          - github.com/CosmWasm/wasmd
          - github.com/CosmWasm/wasmvm

          - github.com/cosmos/gogoproto

          - github.com/golang/protobuf/proto

          - github.com/google/uuid

          - github.com/gorilla/mux

          - github.com/grpc-ecosystem/grpc-gateway

          - github.com/hashicorp/go-metrics

          - github.com/provenance-io/provenance

          - github.com/rakyll/statik/fs 

          - github.com/spf13/cast
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/spf13/viper

          - github.com/stretchr/testify/require # used by the test-utils shared toolkit
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/suite

          - github.com/cometbft/cometbft/abci/types
          - github.com/cometbft/cometbft/config
          - github.com/cometbft/cometbft/crypto
          - github.com/cometbft/cometbft/crypto/tmhash
          - github.com/cometbft/cometbft/libs/cli
          - github.com/cometbft/cometbft/libs/json
          - github.com/cometbft/cometbft/libs/os
          - github.com/cometbft/cometbft/libs/rand
          - github.com/cometbft/cometbft/proto/tendermint/types
          - github.com/cometbft/cometbft/rpc/jsonrpc/types
          - github.com/cometbft/cometbft/types
          - github.com/cometbft/cometbft/types/time
          - github.com/cometbft/cometbft-db

          - github.com/rs/zerolog

          - sigs.k8s.io/yaml
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/stretchr/testify

  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/cometbft)
      - prefix(cosmossdk.io)
      - prefix(github.com/cosmos)
      - prefix(github.com/provenance-io)
      - blank
      - dot
  govet:
    shadow: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  # gocyclo:
  #   min-complexity: 15
  dogsled:
    max-blank-identifiers: 3
  misspell:
    locale: US
    ignore-words:
    - cancelled
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
