version: 2
run:
  tests: false
#   # timeout for analysis, e.g. 30s, 5m, default is 1m
#   timeout: 5m
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - errname
#    - forcetypeassert
    - goconst
    - gocritic
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - usetesting
    # - stylecheck
    # - tenv
    # - gosimple
formatters:
  enable:
    - gofmt
    - goimports
    - gci
issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec
    - text: "comment on exported var"
      linters:
        - revive
    - text: "don't use an underscore in package name"
      linters:
        - revive
    - text: "don't use underscores in Go names; const (TxEndpoint|TLCategory|TLType|TLAction)_"
      linters:
        - revive
    - text: "ST1003:"
      linters:
        - stylecheck
    - text: "don't use leading k in Go names"
      linters:
        - revive
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters.settings:
  depguard:
    rules:
      main:
        list-type: lax
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          
         # CosmWasm
          - github.com/CosmWasm
          - github.com/CosmWasm/wasmd
          - github.com/CosmWasm/wasmd/x/wasm 
          - github.com/CosmWasm/wasmvm/v2

          # CosmWasm Legacy Protos
          - github.com/provenance-io/provenance/legacy_protos/cosmwasm/wasm/v1beta1

          # Cosmossdk.io
          - cosmossdk.io
          - cosmossdk.io/api
          - cosmossdk.io/client/v2
          - cosmossdk.io/collections
          - cosmossdk.io/core
          - cosmossdk.io/errors
          - cosmossdk.io/log
          - cosmossdk.io/math
          - cosmossdk.io/store
          - cosmossdk.io/x/circuit
          - cosmossdk.io/x/evidence
          - cosmossdk.io/x/feegrant
          - cosmossdk.io/x/nft
          - cosmossdk.io/x/tx/signing
          - cosmossdk.io/x/upgrade

          # Cosmos
          - github.com/cosmos/cosmos-db
          - github.com/cosmos/cosmos-sdk
          - github.com/cosmos/go-bip39
          - github.com/cosmos/gogoproto
          - github.com/cosmos/gogoproto/proto
          - github.com/golang/protobuf/proto

          - github.com/google/uuid

          - github.com/gorilla/mux

          - github.com/grpc-ecosystem/grpc-gateway

          - github.com/hashicorp/go-metrics

          - github.com/provenance-io/provenance

          - github.com/provlabs/vault

          - github.com/spf13/cast
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/spf13/viper

          - github.com/stretchr/testify/require # used by the test-utils shared toolkit
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/suite

          # CometBFT
          - github.com/cometbft/cometbft-db
          - github.com/cometbft/cometbft/abci/types
          - github.com/cometbft/cometbft/config
          - github.com/cometbft/cometbft/crypto
          - github.com/cometbft/cometbft/crypto/tmhash
          - github.com/cometbft/cometbft/libs/cli
          - github.com/cometbft/cometbft/libs/json
          - github.com/cometbft/cometbft/libs/os
          - github.com/cometbft/cometbft/libs/rand
          - github.com/cometbft/cometbft/proto/tendermint/types
          - github.com/cometbft/cometbft/rpc/jsonrpc/types
          - github.com/cometbft/cometbft/types
          - github.com/cometbft/cometbft/types/time

          # Provenance
          - github.com/provenance-io/provenance
          - github.com/provenance-io/provenance/x/trigger/types
          - github.com/provenance-io/provenance/x/trigger/keeper
          - github.com/provenance-io/provenance/x/trigger/types
          - github.com/provenance-io/provenance/x/trigger
          - github.com/provenance-io/provenance/x/trigger/client/cli
          - github.com/provenance-io/provenance/x/trigger/simulation
          - github.com/provenance-io/provenance/testutil
          - github.com/provenance-io/provenance/testutil/assertions
          - github.com/provenance-io/provenance/testutil/contracts
          - github.com/provenance-io/provenance/testutil/queries
          - github.com/provenance-io/provenance/testutil
          - github.com/provenance-io/provenance/x/attribute
          - github.com/provenance-io/provenance/x/attribute/keeper
          - github.com/provenance-io/provenance/x/attribute/types
          - github.com/provenance-io/provenance/x/attribute/simulation
          - github.com/provenance-io/provenance/x/exchange
          - github.com/provenance-io/provenance/x/exchange/client/cli
          - github.com/provenance-io/provenance/x/exchange/keeper
          - github.com/provenance-io/provenance/x/exchange/simulation
          - github.com/provenance-io/provenance/x/exchange/module
          - github.com/provenance-io/provenance/x/flatfees/client/cli
          - github.com/provenance-io/provenance/x/flatfees/keeper
          - github.com/provenance-io/provenance/x/flatfees/module
          - github.com/provenance-io/provenance/x/flatfees/types
          - github.com/provenance-io/provenance/x/flatfees/simulation
          - github.com/provenance-io/provenance/x/hold
          - github.com/provenance-io/provenance/x/hold/keeper
          - github.com/provenance-io/provenance/x/hold/module
          - github.com/provenance-io/provenance/x/hold/simulation
          - github.com/provenance-io/provenance/x/ibchooks
          - github.com/provenance-io/provenance/x/ibchooks/keeper
          - github.com/provenance-io/provenance/x/ibchooks/types
          - github.com/provenance-io/provenance/x/ibcratelimit
          - github.com/provenance-io/provenance/x/ibcratelimit/keeper
          - github.com/provenance-io/provenance/x/ibcratelimit/module
          - github.com/provenance-io/provenance/x/ibcratelimit/simulation
          - github.com/provenance-io/provenance/x/ibchooks/simulation
          - github.com/provenance-io/provenance/x/marker
          - github.com/provenance-io/provenance/x/marker/client/cli
          - github.com/provenance-io/provenance/x/marker/keeper
          - github.com/provenance-io/provenance/x/marker/simulation
          - github.com/provenance-io/provenance/x/marker/types
          - github.com/provenance-io/provenance/x/metadata
          - github.com/provenance-io/provenance/x/metadata/keeper
          - github.com/provenance-io/provenance/x/metadata/types
          - github.com/provenance-io/provenance/x/msgfees/module
          - github.com/provenance-io/provenance/x/metadata/simulation
          - github.com/provenance-io/provenance/x/msgfees/types
          - github.com/provenance-io/provenance/x/msgfees/keeper
          - github.com/provenance-io/provenance/x/name
          - github.com/provenance-io/provenance/x/name/keeper
          - github.com/provenance-io/provenance/x/name/simulation
          - github.com/provenance-io/provenance/x/name/types
          - github.com/provenance-io/provenance/x/oracle/keeper
          - github.com/provenance-io/provenance/x/oracle/module
          - github.com/provenance-io/provenance/x/oracle/client/cli
          - github.com/provenance-io/provenance/x/oracle/simulation
          - github.com/provenance-io/provenance/x/oracle/types
          - github.com/provenance-io/provenance/x/quarantine
          - github.com/provenance-io/provenance/x/quarantine/keeper
          - github.com/provenance-io/provenance/x/quarantine/module
          - github.com/provenance-io/provenance/x/quarantine/simulation
          - github.com/provenance-io/provenance/x/sanction
          - github.com/provenance-io/provenance/x/sanction/keeper
          - github.com/provenance-io/provenance/x/sanction/module
          - github.com/provenance-io/provenance/x/sanction/simulation
          - github.com/provenance-io/provenance/x/trigger/module
          - github.com/provenance-io/provenance/x/trigger
          - github.com/provenance-io/provenance/x/trigger/client/cli
          - github.com/provenance-io/provenance/x/trigger/simulation
          - github.com/provenance-io/provenance/x/wasm/types
          
          # Standard Libraries / Tools
          - github.com/armon/go-metrics
          - github.com/golang/protobuf/proto
          - github.com/google/uuid
          - github.com/gorilla/mux
          - github.com/grpc-ecosystem/grpc-gateway
          - github.com/hashicorp/go-metrics
          - github.com/rs/zerolog
          - github.com/spf13/cast
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/spf13/viper
          - google.golang.org/grpc
          - google.golang.org/grpc/codes
          - google.golang.org/grpc/status
          - google.golang.org/protobuf/runtime/protoiface
          - google.golang.org/protobuf/proto
          - google.golang.org/protobuf/reflect/protoreflect
          - google.golang.org/protobuf/reflect/protoregistry
          - google.golang.org/protobuf/protoadapt

          # Testing
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require # used by the test-utils shared toolkit
          - github.com/stretchr/testify/suite
          
          # Kubernetes / YAML
          - sigs.k8s.io/yaml
        deny:
          - pkg: "github.com/cosmos/cosmos-sdk/x/params"
            desc: "The params module is no more."
      test:
        list-type: lax
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/stretchr/testify
  errcheck:
    exclude-functions:
      - (fmt.State).Write
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/provenance-io)
      - blank
      - dot
  govet:
    shadow: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  # gocyclo:
  #   min-complexity: 15
  dogsled:
    max-blank-identifiers: 3
  misspell:
    locale: US
    mode: default
    ignore-rules:
    - cancelled
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
