version: "3"

services:
  provenance:
    image: rosetta-ci:latest
    command: [
        "provenanced",
        "-t",
        "--home", "/test/run/provenanced",
        "start",
        "--pruning", "nothing",
    ]
#    ports:
#      - "9090:9090"
#      - "26656-26657:26656-26657"
#      - "1317:1317"
    expose:
      - "9090"
      - "26656-26657"
      - "1317"
    environment:
      - ID=0
      - LOG=${LOG:-provenanced.log}
      - PIO_HOME=/provenance
    volumes:
        - ./build:/provenance:Z

  rosetta:
    image: rosetta-ci:latest
    command: [
      "provenanced",
      "rosetta",
      "--blockchain", "provenance",
      "--network", "testing",
      "--tendermint", "provenance:26657",
      "--grpc", "provenance:9090",
      "--addr", ":8080",
      "--testnet", "true",
      "--home", "/test/run/provenanced",
    ]
    ports:
      - "8080:8080"

  faucet:
    image: rosetta-ci:latest
    working_dir: /rosetta
    command: ["python3", "faucet.py"]
    expose:
      - "8080"

  test_rosetta:
    image: tendermintdev/rosetta-cli:v0.6.7
    volumes:
      - ./configuration:/rosetta/config:z
    command: ["./config/run_tests.sh"]
    working_dir: /rosetta