version: "3.3"

services:
  provenanced:
    image: rosetta-ci:latest
    command: [
        "provenanced",
        "start",
        "--home", "/test/run/provenanced",
    ]
    ports:
      - 9090:9090
      - 26657:26657
    logging:
      driver: "none"

  rosetta:
    image: rosetta-ci:latest
    volumes:
      - ./build:/rosetta/build:z
    command: [
      "provenanced",
      "rosetta",
      "--blockchain", "provenanced",
      "--network", "testing",
      "--tendermint", "cosmos:26657",
      "--grpc", "cosmos:9090",
      "--addr", ":8080",
      "--home", "/test/run/provenanced",
    ]
    ports:
      - 8080:8080

  faucet:
    image: rosetta-ci:latest
    working_dir: /rosetta
    command: ["python3", "faucet.py"]
    expose:
      - 8080

  test_rosetta:
    image: tendermintdev/rosetta-cli:v0.6.7
    volumes:
      - ./configuration:/rosetta/config:z
    command: ["./config/run_tests.sh"]
    working_dir: /rosetta
