global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    local:
        type: cosmos
        value:
            key: default
            chain-id: testing
            rpc-addr: http://192.168.20.2:26657
            account-prefix: tp
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 1905nhash
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
    local2:
        type: cosmos
        value:
            key: default
            chain-id: testing2
            rpc-addr: http://192.168.20.3:26657
            account-prefix: tp
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 1905nhash
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct

paths:
    local_local2:
        src:
            chain-id: testing
        dst:
            chain-id: testing2
        src-channel-filter:
            rule: ""
            channel-list: []