name: buf-release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/provenance-io/provenance.git#branch=main'
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'third_party/proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/provenance-io/provenance.git#branch=main'
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'third_party/proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
