name: Tests / Code Coverage
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to master & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - main
jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  #  This action performs a code coverage assessment but filters out generated code from proto based types
  #  and grpc services
  test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
      with:
        # CodeCov requires fetch-depth > 1
        fetch-depth: 2
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
    - name: Display go version
      run: go version
    - name: test & coverage report creation
      run: make test-cover
    - name: filter out DONTCOVER
      run: |
        excludelist="$(find ./ -type f -name '*.go' | xargs grep -l 'DONTCOVER')"
        excludelist+=" $(find ./ -type f -name '*.pb.go')"
        excludelist+=" $(find ./ -type f -name '*.pb.gw.go')"
        excludelist+=" $(find ./ -type f -path './tests/mocks/*.go')"
        for filename in ${excludelist}; do
          filename=$(echo $filename | sed 's/^./github.com\/provenance\-io\/provenance/g')
          echo "Excluding ${filename} from coverage report..."
          sed -i "/$(echo $filename | sed 's/\//\\\//g')/d" coverage.txt
        done
    - uses: codecov/codecov-action@v1.0.14
      with:
        file: ./coverage.txt
