name: Rosetta
# Rosetta runs rosetta-cli to verify that provenance still meets the Rosetta api
on:
  pull_request:
  push:
      branches:
        - main

# Set concurrency for this workflow to cancel in-progress jobs if retriggered.
# The github.ref is only available when triggered by a PR so fall back to github.run_id for other cases.
# The github.run_id is unique for each run, giving each such invocation it's own unique concurrency group.
# Basically, if you push to a PR branch, jobs that are still running for that PR will be cancelled.
# But jobs started because of a merge to main or a release tag push are not cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  rosetta:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            client/rosetta/**
            .github/workflows/rosetta.yml
      - uses: actions/setup-go@v4
        if: ${{ env.GIT_DIFF }}
        with:
          go-version: '1.20'
      - name: Go mod vendor
        if: ${{ env.GIT_DIFF }}
        run: |
          go mod vendor
      - name: rosetta
        if: ${{ env.GIT_DIFF }}
        run: make test-rosetta
